- hosts: TARGET

  vars:
##    include_vars:
##      file: /home/root/Ansible/USERS/groups.yml
##      name: groups

##      file: /home/root/Ansibel/USERS/users.yml
##      name: users

############################################
# CHANGES
# 2020/01/31 - new usernames for all dev accounts
# 
###########################################
#      - login: ECABuildRelease
#        groups:
#        password:
#      - login: ECAReleaseBuilder
#        groups:
#  - import_playbook: snmp_config.yml

  handlers:
    - name: "Restart sshd"
      service:
        name: "sshd"
        state: "restarted"

  tasks:
## TINTERNET CHECK
  - name: Use uri to check t'internet
    uri:
      url: http://scootersoftware.com
      return_content: no
      timeout: 10
    register:  tinternet_disabled
    failed_when: "{{ tinternet_disabled.msg == 'Status code was -1 and not [200]:' }}"
    ignore_errors: true
  - debug:
#      msg: "{{ tinternet_disabled.status }}"
      msg: "{{ tinternet_disabled }}"

  - name: include Groups VARS file
    include_vars: /root/Ansible/USERS/groups.yml
    name: groups

  - name: include Groups VARS file
    include_vars: /root/Ansible/USERS/users.yml
    name: users


## ADD ADMIN USERS AND GROUPS
# Add sp_users group
  - name: Add sp_users group
    group:
     name: sp_users
     state: present

# Add xrdpusers group
  - name: Add xrdpusers group
    group:
     name: xrdpusers
     state: present

##  - include_vars:
##      file: USERS/groups.yml
##      name: groups
##      file: USERS/users.yml
##      name: users

  - name: Create groups ahead of accounts
    group:
     name: "{{ item.groups }}"
    with_items:
      - "{{ admin_groups }}"
      - "{{ dev_groups }}"

  - name: Add USERS/users.yml accounts locally
    user:
      name: "{{ item.login }}"
      groups: "{{ item.groups }}"
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      comment: "{{ item.login }}"
      append: yes
#      password: "{{ item.password }}"
#      update_password: on_create
    with_items:
      - "{{ admin_users }}"
      - "{{ dev_users }}"

# Remove users specified
  - name: Rmeove users specified in remove_users list
    user:
      name:  "{{ item.login }}"
      state: absent
    with_items:
      - "{{ remove_users }}"

# Add sp_users entries to /etc/sudoers
  - name: Adding sp_users to /etc/sudoers
    lineinfile:
      owner: root
      group: root
      dest: /etc/sudoers
      backup: yes
      validate: /usr/sbin/visudo -cf %s
      line: '{{ item }}'
    with_items:
      - ''
      - '## sp_users'
      - 'Cmnd_Alias SP_USERS = /bin/firewall-cmd, /bin/systemctl, /sbin/reboot, /usr/bin/vi /etc/hosts, /bin/vim /etc/hosts, /usr/bin/su -'
      - '%sp_users      ALL=(ALL)        SP_USERS'


# Setup ACL's for devs group (excludes read/write access to DevMan and DevLead)
# 30/01/2020 - /etc/ECA added for devs ACL group
  - name:  Add ACL for devs group to /home accounts excluding DevMan and DevLead users + /etc/ECA
    acl:
      path: "{{ item }}"
      entity: devs
      etype: group
      permissions: rwx
      state: present
    loop:
      - /home/gksd
      - /home/ssasd
      - /home/apsd
      - /home/shsd
      - /home/iksd

# Setup ACL's for DevLead group(excludes read/write access to DevLead)
  - name:  Add ACL for DevMan group to /home accounts excluding DevLead users
    acl:
      path: "{{ item }}"
      entity: DevLead
      etype: group
      permissions: rwx
      state: present
    loop:
      - /home/gksd
      - /home/ssasd
      - /home/apsd
      - /home/shsd
      - /home/ngsd
      - /home/iksd
      - /home/mmsd
      - /home/wgsd

# Setup ACL's for DevLead group(read/write access to everything)
  - name:  Add ACL for DevLead group to all /home accounts
    acl:
      path: "{{ item }}"
      entity: DevMan
      etype: group
      permissions: rwx
      state: present
    loop:
      - /home/gksd
      - /home/ssasd
      - /home/apsd
      - /home/shsd
      - /home/ngsd
      - /home/iksd
      - /home/mmsd
      - /home/wgsd
      - /home/ngsd
      - /home/rssd

  - name:  Add ACL for devs group to /etc/ECA
    acl:
      path: "{{ item }}"
      entity: devs
      etype: group
      permissions: rwx
      state: present
    loop:
      - /etc/ECA

  - name:  Add ACL for DevLead group to /etc/ECA
    acl:
      path: "{{ item }}"
      entity: DevLead
      etype: group
      permissions: rwx
      state: present
    loop:
      - /etc/ECA

  - name:  Add ACL for DevMan group to /etc/ECA
    acl:
      path: "{{ item }}"
      entity: DevMan
      etype: group
      permissions: rwx
      state: present
    loop:
      - /etc/ECA


# Clean up old Development rules/entires in /etc/sudoers
  - name: removing legacy devs entry (used vi for /etc/hosts which is insecure)
    lineinfile:
      owner: root
      group: root
      dest: /etc/sudoers
      backup: yes
      validate: /usr/sbin/visudo -cf %s
      line: '{{ item }}'
      state: absent
    with_items:
      - ''
      - '## Developers'
      - 'Cmnd_Alias DEVS =  /bin/firewall-cmd, /bin/systemctl, /sbin/reboot, /usr/bin/vi /etc/hosts, /bin/vim /etc/hosts, /usr/bin/update-ca-trust extract, /usr/bin/cp *.crt /etc/pki/tls/certs, /usr/bin/ln -sv /etc/pki/tls/certs/*.crt /etc/pki/tls/certs/*.0, /bin/openssl x509 -in /etc/pki/tls/certs/*.crt -noout -hash'
      - '%devs          ALL = NOPASSWD: DEVS'

# Add devs entries to /etc/sudoers
  - name: Adding devs to /etc/sudoers
    lineinfile:
      owner: root
      group: root
      dest: /etc/sudoers
      backup: yes
      validate: /usr/sbin/visudo -cf %s
      line: '{{ item }}'
    with_items:
      - ''
      - '## Developers'
      - 'Cmnd_Alias DEVS = /bin/firewall-cmd, /bin/systemctl, /sbin/reboot, /usr/bin/update-ca-trust extract, /usr/bin/cp *.crt /etc/pki/tls/certs, /usr/bin/ln -sv /etc/pki/tls/certs/*.crt /etc/pki/tls/certs/*.0, /bin/openssl x509 -in /etc/pki/tls/certs/*.crt -noout -hash, /usr/bin/cp *.crt /etc/pki/ca-trust/source/anchors/'
      - '%devs          ALL = NOPASSWD: DEVS, sudoedit /etc/hosts'


## Remove the admin account used for initial POST OS build/replaced with Break Glass acocunt
  - name: Remove the admin account used for initial POST OS build/replaced with Break Glass acocunt
    user:
     name: admin
     state: absent
